monitor.alsa.rules = [
    {
        matches = [ { node.name = "alsa_output.platform-sound.RawSpeakers" } ]
        actions = {
            update-props = {
                api.alsa.headroom = 4096
                api.alsa.period-size = 2048
                api.alsa.disable-tsched = true
            }
        }
    }
]
